// <auto-generated />
namespace TripSplit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StartandEndlocationchangedtomatchgoogleapiformatdeletedwaypoint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StartandEndlocationchangedtomatchgoogleapiformatdeletedwaypoint));
        
        string IMigrationMetadata.Id
        {
            get { return "201703171533316_Start and End location changed to match google api format, deleted waypoint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
