// <auto-generated />
namespace TripSplit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedfriendemailnumbertotrip : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedfriendemailnumbertotrip));
        
        string IMigrationMetadata.Id
        {
            get { return "201703240353299_added friendemail number to trip"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
