// <auto-generated />
namespace TripSplit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedthemetableandaddedFKonTriptable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedthemetableandaddedFKonTriptable));
        
        string IMigrationMetadata.Id
        {
            get { return "201703172152511_added theme table and added FK on Trip table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
